1 PRINT CHR$(147)
2 INPUT A
3 IF A = 0 THEN END
4 PRINT STR$(ABS((A AND 128)=128))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 64)=64))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 32)=32))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 16)=16))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 8)=8))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 4)=4))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 2)=2))"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"+STR$(ABS((A AND 1)=1))+"{CURSOR LEFT}{DEL}{CURSOR RIGHT}"
5 PRINT ""
6 GOTO 2
